apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-argo-app
spec:
  selector:
    matchLabels:
      app: demo-argo-application
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-argo-application
    spec:
      containers:
      - name: myapp
        image: vrreddy1992/argo-cd-demo:1.0
        ports:
        - containerPort: 8080
